server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/{segment:products|categories|suppliers|product-variants}/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/payments/**
          filters:
            - StripPrefix=1