server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/{segment:products|categories|suppliers|product-variants}/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/payments/**
          filters:
            - StripPrefix=1
        - id: review-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/reviews/**
          filters:
            - StripPrefix=1
        - id: sale-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/sales/**
          filters:
            - StripPrefix=1