server:
  port: 8084
  servlet:
    context-path: /payments
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopsphere-order?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.tuanha.payment.dto.request.PaymentNotificationRequest

