server:
  port: 8083
  servlet:
    context-path: /orders
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopsphere-order?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.tuanha.order.kafka.OrderConfirmation

app:
  services:
    product: http://localhost:8082
    profile: http://localhost:8081/profile/users
    payment: http://localhost:8084/payments

