server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopsphere-product?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

firebase:
  bucket-name: gs://shopsphere-62911.appspot.com



